### PR TITLE
resolve #21

### LINKED ISSUE #21: The problem with deleting the record in the fresh versions of react-admin
When you delete a record, you receive an error message in the response format:
"The response to 'DELETE' must be like { data: { id: 123, ... } }, but the received data does not have an 'id' key. The dataProvider is probably wrong for 'DELETE'"

### PR DESCRIPTION
**Pull request by JimmySorza**
Added case for `DELETE` in the index.js with the same return of `CREATE`.  This is because The response to `DELETE` must be like { data: { id: 123, ... } }

- Resolve #21

### CODE REVIEW

**Comment by afilp** [comment]
Hi! Can this be merged? Without this, this lib does not work for DELETE in React Admin 2+

**Comment by JimmySorza** [comment]
@afilp the reason must be this: https://github.com/kimkha/aor-loopback#not-maintained-anymore 

> With new react-admin, please use [loopback-component-react-admin](https://github.com/kimkha/loopback-component-react-admin) instead
> Because of recent changes of admin-on-rest, this module will only support version 0.9.0 (or later) of admin-on-rest.

Then I close this Pull request.

**Comment by afilp** [comment]
@JimmySorza Thank you! So I assume we must follow that other package now. Thanks @kimkha for your work.

**Comment by afilp** [comment]
@JimmySorza Ummm, now I am confused, there is another package also:

https://github.com/darthwesker/react-admin-loopback

And actually this is the one shown in "Data Providers":
https://marmelab.com/react-admin/DataProviders.html

**Comment by JimmySorza** [comment]
you right!, I did not know about that other package, so you can use any package you want.

**Pull request closed without merging**
